version: '3.8'
services:
  collector:
    build: .
    container_name: mikrotik-collector
    command: ["python", "run_api_collector.py", "--config", "mi_config.json"]
    environment:
      - STATE_DB_PATH=/app/state_api.db
    volumes:
      - ./state_api.db:/app/state_api.db
      - ./mi_config.json:/app/mi_config.json:ro
    ports:
      - "9102:9102"
      - "5000:5000"

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./extras/blackbox/blackbox.yml:/config/blackbox.yml:ro
    command: ["--config.file=/config/blackbox.yml"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./extras/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - blackbox
      - collector

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data: {}
