global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mikrotik_collector'
    static_configs:
      - targets: ['collector:9102']

  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 1.1.1.1
        - 8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'blackbox_tcp_8728'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - router.example.local:8728
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*):(\d+)
        replacement: $1
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
